apiVersion: v1
kind: Namespace
metadata: 
  name: mynamespace1
---
apiVersion: v1
kind: Service
metadata:
  name: myappservice
  namespace: mynamespace1
spec:
  selector:
    app: app1
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment1
  namespace: mynamespace1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: app1
    spec:
      terminationGracePeriodSeconds: 60  # Corrected the field name here
      minReadySeconds: 10                # Corrected the field name here
      containers:
      - name: mycontainer1
        image: jayantborate14/mithuntechnologies:apache2.2
        ports:
        - containerPort: 80
